function [fitresult, gof,ci] = createFitPercO(X, M3)
% Glazier, Brockman, Bartle, Mattheyses, Destaing, and Salaita. 2019. 
%CREATEFIT(X,M3)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X
%      Y Output: M3
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-May-2018 12:28:54


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( X, M3 );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [2.51316670639984 0.000751171767178946 -1.41081352983681 -0.0392039265713077];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
ci = confint(fitresult,.95);
% Plot fit with data.
figure( 100);
h = plot( fitresult, xData, yData );
legend( h, 'M3 vs. X', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel X
ylabel M3
grid on


