function [] = ClusterFinder(indivcells, StackName)
% Glazier, Brockman, Bartle, Mattheyses, Destaing, and Salaita. 2019. 
% The input of this function is a single FLIM timestack cell generated by
% Cells2Track. 
% Glazier, Brockman, Bartle, Mattheyses, Destaing, and Salaita. 2019. 
% There is no direct output of this function, but a mask of clusters wills
% save as a tifstack in the current folder. 
time = length(indivcells); 

% Perform a tophat filter on intensity images
for j=1:time
    SE=strel('disk',10);
    THICell{j} = imtophat(indivcells{j,1},SE)
end

% Define background and SD
[Int, Dev, rectan, ROIC]= MeanI(THICell{time});
for j=1:time
rectan=THICell{j}(ROIC(2,1):ROIC(2,2),ROIC(1,1):ROIC(1,2));
IntensB{j,1}=mean(rectan(:),'omitnan');
DevB{j,1}=std(rectan(:),'omitnan');
end
%subplot(1,3,1); imshow(THICell{j},[]);
% subplot(1,3,2); imshow(bwareaopen(bwmorph(bwmorph(THICell{j}<(IntensB{j,1}-1.5*DevB{j,1}),'clean'),'spur'),10));
% If these conditions do not work well for your images, you can adjust the
% parameters and view by uncommenting the two lines above. It is not
% perfect, but quite good with our data. 
for j= 1:time
Ifilt{j,1}=bwareaopen(bwmorph(bwmorph(THICell{j}<(IntensB{j,1}-1.5*DevB{j,1}),'clean'),'spur'),10);
Ifilt{j,2}=imdilate(Ifilt{j,1},strel('disk',5));

    
      
      figure(7);
    subplot(2,2,1); imshow(THICell{j},[]);
    Ifilt{j,3}=bwmorph(bwareafilt(THICell{j}>(IntensB{j,1}+2*DevB{j,1}),[5 120]),'majority'); %clutsers + some pods?
    APMFmaker{j}=double(Ifilt{j,3});
    APMFmaker{j}(APMFmaker{j}==0)=.8;
    APMFmaker{j}(APMFmaker{j}==1)=0;
    DIM=cat(3, zeros(433), zeros(433), zeros(433));
   
    figure(7);
     
    subplot(2,2,2); imshow(Ifilt{j,3});
    subplot(2,2,3); imshow(Ifilt{j,2});
    Ifilt{j,4}=bwareaopen(Ifilt{j,3}.*~Ifilt{j,2},3);
   subplot(2,2,4); imshow(Ifilt{j,4},[]);
   
   




end

% Save as TiffStack
clear options;
options.append = true;

for k=1:time
   
   saveastiff(uint32(Ifilt{k,4}),StackName,options);
   saveastiff(uint32(Ifilt{k,4}.*THICell{k}),StackName,options);
end

end