   function [Masking] = KymoMasking(Stack)
   % Glazier, Brockman, Bartle, Mattheyses, Destaing, and Salaita. 2019. 
%This function is used to generate NANMasks for a video to make Kymographs.
% The input is a Cell array of the FLIM time lapse generated by
% Cells2Track.
T = length(Stack);
for j=1:T
    
    CCut= Stack{j,1}<25;
    LCut= Stack{j,2}>2.97.*10^-9;
    Masking{j}=double(CCut | LCut);
end
end

